// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5E1_Lnt_s99g4pwbzSeWmZ-d2YJWq6Wo',
    appId: '1:393491289936:web:6d77759f59dd94d9207e55',
    messagingSenderId: '393491289936',
    projectId: 'mis-lab-e31c0',
    authDomain: 'mis-lab-e31c0.firebaseapp.com',
    storageBucket: 'mis-lab-e31c0.firebasestorage.app',
    measurementId: 'G-KG8L4SVBSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARDtSjU7FV5YRwgu55XwamZ6tVGwrQDxo',
    appId: '1:393491289936:android:7b183a76434eb3b8207e55',
    messagingSenderId: '393491289936',
    projectId: 'mis-lab-e31c0',
    storageBucket: 'mis-lab-e31c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHwUfYKPHgov9LXxfCj0rHneMEsfNQWrg',
    appId: '1:393491289936:ios:1d814e71a11761cf207e55',
    messagingSenderId: '393491289936',
    projectId: 'mis-lab-e31c0',
    storageBucket: 'mis-lab-e31c0.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

}